### ISSUE TITLE
[UX]: Tell user when they make a mistake in the domain part of their XMPP address

### ISSUE THREAD

**Issue by haansn08** [monal-im/Monal#1007]
### What Monal Release channel are you using?

AppStore

### Used XMPP server (domain)

does-not-apply.tld

### Which XMPP-Server software are you using?

None

### How many accounts are you using in Monal?

1

### What happened?

A friend of mine recently had to re-login into Monal and had her address saved in her password manager as `friend@yax.at` instead of `friend@yax.im`. She could not figure out why it doesn't work because the error message only said "timeout" instead of something more specific like "no such server" or even "could not resolve domain `yax.im`: timeout" which might be more confusing to users, but at least somebody technical can figure out that the problem is with the domain, not the server or Monal itself. Currently it seems to be hard to figure out what went wrong if you enter a bad address.

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
No, it doesn't just say "timeout", it says `We were not able to connect your account. Please check your credentials and make sure you are connected to the internet.`

Since Apple's network framework doesn't tell us why a connection cannot be established but just sits there indefinitely trying to connect, we abort that connect after 30 seconds and show the above text.

Credentials means `username` and `password`. But to be more clear, I've changed that to `We were not able to connect your account. Please check your username and password and make sure you are connected to the internet.` now.
