### ISSUE TITLE
[Feature]: Show and load recent existing chats after installation if available

### ISSUE THREAD

**Issue by Echolon** [monal-im/Monal#1074]
### Precondition

- [X] I understood that this template is only for feature requests and not for bug reports

### Cross-checked related issues?

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### Describe your feature

I think this screen is not expected if you have an existing account with existing chats.

Therefore, I would recommend Monal to check the archive or at least offer a button to do so right away.

![IMG_0178](https://github.com/monal-im/Monal/assets/29168011/6532b74a-36fa-4ce4-a768-09702fc2f308)

**Comment by licaon-kter** [comment]
It does not respect autojoin flag?

**Comment by Echolon** [comment]
I only received entries after a new chat message has been sent to me

5 jun 2024 23:33:32 Licaon_Kter ***@***.***>:

**Comment by tmolitor-stud-tu** [comment]
@licaon-kter It does, I think Echolon meant chats that were active before the first login.

@Echolon First of all, loading old messages would make the login process take significantly longer. And then: what would count as "recently active" in the first place?
And last but not least: that won't work for omemo encrypted chats because of the forward secrecy property of omemo (and omemo is the default nowadays).

--> won't fix

**Comment by Echolon** [comment]
Wouldn't it be possible to gather the chats that happened in the last hour or so and not load many messages? The rest  the user could trigger or trigger when chat is being opened?

**Comment by tmolitor-stud-tu** [comment]
As I said: even when gathering the last hour worth of messages, Monal won't be able to decrypt them.
