### ISSUE TITLE
Monal should respect a chatroom's permission settings

### ISSUE THREAD

**Issue by lissine0** [monal-im/Monal#1081]
### Precondition

- [X] I understood that this template is only for feature requests and not for bug reports

### Cross-checked related issues?

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### Describe your feature

MUCs have settings like `muc#roomconfig_changesubject` and `muc#roomconfig_allowinvites` which specify whether a member has the ability to invite other members to the MUC, or to edit the subject.
Monal should parse these values and respect them.

Note: the MUC XEP had a wrong example using `muc#roominfo_changesubject` instead of `muc#roomconfig_changesubject`
Most implementations followed the wrong example.
This was fixed in prosody years ago and in ejabberd 9 months ago.
You may want to check for both strings to be compatible with old ejabberd servers and (potentially incorrect) other server software

**Comment by tmolitor-stud-tu** [comment]
Well, honoring `muc#roomconfig_changesubject` is easy. Currently you are allowed to change the subject if you have the moderator role and it shows an error message if you try to do so and aren't allowed to do it.

`muc#roomconfig_allowinvites` on the other hand is special. This setting only applies to MUC mediated invites, not XEP-0249 direct invites. Monal sends out both, medaited and direct invites (mediated might not work, because of clients/servers blocking messages from jids not in a user's roster).

I'd leave that one as is. As with the room subject setting, trying to do a mediated invite in a room not supporting this, will result in an error message.

Additionally, I believe that even in a room not allowing mediated invites, a room admin or owner is always allowed to invite users to that room. And Monal only shows the invite button in the UI if the user is admin/owner in the first place.

**Comment by tmolitor-stud-tu** [comment]
Okay, I read XEP-0045 on room subject changes, and I think Monal will not support room subject changes for normal participants not having a moderator role and likewise not allow subject changes for users not having a moderator role. Both cases are super rare.

I close this issue now.

**Comment by lissine0** [comment]
I did not explain my self well earlier.
Owners (and admins?) are always allowed to edit the subject and to invite others, regardless of the value of these settings.
These settings say whether _eveyone_ can edit the subject or invite others.
I think at least the inviting part is useful.

Being part of a group chat's config, I thought the only thing needed was showing the relevant UI to normal users if the settings are set to true.

(In fact, these are the only settings in the configuration form that Conversations allows to be _edited_, aside from the title and subject)

**Comment by tmolitor-stud-tu** [comment]
> Being part of a group chat's config, I thought the only thing needed was showing the relevant UI to normal users if the settings are set to true.

Yes and no. Show the invite settings only to users in a members-only group or to users in a channel, too? The UI for channels is very different from the one for members-only groups.

According to my observations, these functions are generally very rarely used. I don't think its worth the time to implement these. But you can always create a pull request, if you want :)
