### ISSUE TITLE
[Enhancement]: Change the default target view of contact request notifications

### ISSUE THREAD

**Issue by lissine0** [monal-im/Monal#1114]
### Precondition

- [X] I understood that this template is only for feature requests and not for bug reports

### Cross-checked related issues?

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### Describe your feature

Monal's contact request iOS notifications have "approve new contact" and "deny new contact" actions, but you need to long click the notification to see them.
There's also an iOS-builtin "open" action. (which is the default if you simply click the notification from within the app)
Currently, choosing this action takes you to the contact's chat view, without accepting nor rejecting their request.
Shouldn't it take you to the Contact Requests view?

**Comment by lissine0** [comment]
Video illustration of clicking the notification from within the app:

https://github.com/user-attachments/assets/d3b05f69-50cc-4f58-ab26-4028de5cdb01

**Comment by tmolitor-stud-tu** [comment]
Well, that was intentional to allow users to chat with this person without having to answer the contact request (yet).
The new chat view will show a floating warning that this contact has an open contact request.

That said, the contact requests view has a button to open a chat without accepting or rejecting the request, too. So opening the contact requests view would be a possible option, too.

What do you think is better (taking in account the planned floating warning)?

**Comment by lissine0** [comment]
I think it makes more sense to take you to the contact requests view. That's more natural, especially since we have a proper view for contact requests.

It's still possible to chat without answering the contact request by

- clicking the button that does so in the contact requests view
- accessing the chat directly from the Chats view, assuming you or your potential contact already sent a message to the other

The planned floating warning will still be beneficial, as it'll remind the user to add the other person to their roster, so they can have a better experience (A/V calls, presence etc.)

**Comment by tmolitor-stud-tu** [comment]
okay, thanks for your insights :)
