### ISSUE TITLE
[Bug]: Connecting to LDAP auth backed ejabberd 24.06 fails with SASL2-SCRAM unsupported error

### ISSUE THREAD

**Issue by enbyfoxen** [monal-im/Monal#1186]
### What Monal Release channel are you using?

AppStore

### macOS system version (if applicable)

14.5

### Monal version

6.4.1

### Used XMPP server (domain)

blahaj.space

### Which XMPP-Server software are you using?

ejabberd

### XMPP Server Software Version

24.06

### How many accounts are you using in Monal?

2

### What happened?

After upgrading ejabberd to 24.06, monal reports "Server suddenly lacks support for SASL2-SCRAM, ongoing MITM attack highly likely [...]".

This server uses the LDAP backend for auth, SASL2-SCRAM is not supported in this configuration, and was never enabled in the past.
Up until before this upgrade, monal worked with the same server configuration.
Dino continues to work.

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
That should not happen since the app has an internal counter to check if it ever succeeded using SASL2 with SCRAM. Can you provide a logfile via email to info@monal-im.org

See https://github.com/monal-im/Monal/wiki/Introduction-to-Monal-Logging

**Comment by tmolitor-stud-tu** [comment]
Please send the 2 newest logfiles to counter a possibly rotated logfile.

**Comment by enbyfoxen** [comment]
Log files have been sent as requested.

**Comment by tmolitor-stud-tu** [comment]
Thanks, I'm not sure if I manage to analyze them before my vacation.

-tmolitor


Am Samstag, 3. August 2024, 20:57:57 CEST schrieb Lilian:
> Log files have been sent as requested.

**Comment by tmolitor-stud-tu** [comment]
I need more logfiles (see my mail).

In the meantime some explanations:
Monal offers only PLAIN auth for SASL1 and only SCRAM for SASL2.
The database has a field recording if SASL2 was used at least once and that disables SASL1.
The database has a second field recording if PLAIN auth is needed on a server and if so, SASL2 isn't tried, falling back to SASL1.
If Monal sees that SASL2 with something better than PLAIN is advertised during SASL1 authentication, it switches that "plain needed" flag off and restarts authentication.
This retriggered auth will use SASL2 and thus switch the "SASL2 used at least once" field in the db on. This flag will prevent SASL1 auth.

To allow seamless server upgrades for accounts already present when the server did only suppot SASL1 and these flags weren't present in the DB, the database upgrade to Monal 6.2 flipped the flags to `plain_activated=true, supports_sasl2=false` (default would be both false).

And I guess here is the bug you hit: these flags were only flipped for accounts not enabled and having the `supports_sasl2` set when the DB upgrade was done. That's obviously wrong, since already activated accounts not supporting SASL2 should have `plain_activated=true`, too, to allow seamless upgrades later on.

Nonetheless more logs would be good to check my theory.

**Comment by tmolitor-stud-tu** [comment]
Since this was a security relevant bug, the only solution for you is to remove the account from monal and set it up again. I'm sorry.
