### ISSUE TITLE
MUC-PM Carbon handling (private message)

### ISSUE THREAD

**Issue by ge0rg** [monal-im/Monal#284]
It would be good if Monal could add special treatment for MUC-PMs, even from MUCs that the client isn't joined to.

You can (more or less reliably) detect a MUC-PM based on [the <x/> element in the message](https://xmpp.org/extensions/xep-0045.html#privatemessage).

Most server implementations will send you "sent" and "received" Carbons of MUC-PMs, which should not be stored as regular messages for the MUC JID, but instead have their own place / namespace.

My Carbon PM treatment is as follows:
* completely ignore "received" MUC-PMs (they are copied by the MUC to all joined clients) - alternatively, you could offer a join dialog / silenty join the MUC when the user wants to reply
* store "sent" PMs into the respective PM tab history

**Comment by tmolitor-stud-tu** [comment]
we won't implement muc pms and will just reply to message stazas carrying a muc pm with an error.

**Comment by licaon-kter** [comment]
@tmolitor-stud-tu Why?

While in a private MUC users can see each others JIDs and talk privately, in a public one there's no mechanism to have them chat privately or exchange JID to do 1:1 later, besides MUC PM.

**Comment by Echolon** [comment]
Dino is showing PMs in a new 1:1 chat. maybe this could be an intermediate suggestion.

**Comment by roman901** [comment]
@Echolon so in #700 I suggests to show MUC PM's like 1:1 chats, this is common way for it

**Comment by tmolitor-stud-tu** [comment]
@licaon-kter because muc pms are conceptually flawed. If the receiver is not connected/having a XEP-198 session open when the sender sends him a pm, the pm will vanish in nirvana and never be seen.
Monal, like other iOS apps, can't maintain a constant connection to the xmpp server and XEP-198 sessions will eventually time out --> missing pms is much more common on iOS than on say android using conversations.

Monal is aiming to be an eay to use client for first-time-xmpp users. Broken muc pms just don't fit in there.

If some poweruser wants to send muc pms he can always use another client.

**Comment by licaon-kter** [comment]
There's no PM option if member is not online :)

**Comment by tmolitor-stud-tu** [comment]
there is no such thing like "online" in iOS/Monal

**Comment by Echolon** [comment]
I agree with @tmolitor-stud-tu. I would like to see working features like this. But all my contacts claim why there is not working voice messages.

Guys, do not forget: Apple xmpp clients are rare and even more hard to develop. Lets focus on the real important topics. Especially, as long as Thilo, Friedrich and Anu have invested infinte hours for no payment.
