### ISSUE TITLE
Add support to allow dragging files into compose box

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#596]
**Currently**

To send a screenshot:

* click clipboard icon in compose box
* select `Files` (I never used and am very unlikely to use `Send Location`)
* navigate to file location
* select file
* click open

**Expected**

Drag file from e.g. desktop into compose box should trigger send. Done.

**Comment by FriedrichAltheide** [comment]
I would prefer a box with all queued files above the text field instead of a automatic send action

**Comment by foss-** [comment]
Triggering send was a bad and false description. Sending should always be triggered by pressing `Enter` to avoid accidental mistakes. So for images would be nice to show a small preview and send on enter allowing to add a message which would then be shown as image description i.e. message right below the image.

Clearly this could be exapnded with image picker and UI to add more images to the selected image (see how Signal handles this). But that is overkill. I would be more than happy with a minimal working darg & drop implementation for now.

**Comment by janst97** [comment]
I'll implement this feature (box containing queued files) with support from @FriedrichAltheide.

**Comment by janst97** [comment]
PR #631 added a basic implementation that would resolve this issue. There are still some remaining problems, but this commit should give insight about how the upload queue with drag and drop support would work from an UI/UX perspective. You can try it out by downloading the current Monal Alpha.

Known problems that will be fixed in the future:
- The add button in the queue should open the file selection menu on catalyst, not a photo picker.
- Basic thumbnail generation for documents does not seem to work reliantly on catalyst right now. I also noticed that a drag is not always recognized.
- The upload process is not nice from an UI perspective (the queue just disappears, it would be more useful to implement some progress bar for each file).
- It would be nice if one was able to drop a file to an active chat without selecting it first (probably a different issue though).
- For non-catalyst releases, there should be a quick shortcut to capture a photo with the camera.

If you have further issues regarding the current implementation, let me know.

**Comment by Echolon** [comment]
@janst97 I understand you want keep this issue open, right?

Anyway - thanks for the great support!

**Comment by tmolitor-stud-tu** [comment]
implemented in alpha

**Comment by foss-** [comment]
Think this could use some fine-tuning:

- drag image to chat view
- with mouse pointer active in compose box press `Enter` key

**Currently**

Nothing

**Expected**

Image should be sent. This becomes even more confusing as I would assume anything that is typed while an image is opened would be sent together with the image in one message (like e.g. signal handles this). But acutally in monal, when typing while image is open and pressing enter, only the text is sent but not the image. This is very confusing.
