### ISSUE TITLE
Allow closing image view using ESC key

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#647]
**Currently**
mouse has to be moved over image preview and close be clicked. Click and scroll up / down to close is also possible (guess this is catalyst porting iOS two finger scrolling over to macOS).

**Expected**
`ESC` key should also close image preview.

**Comment by foss-** [comment]
EDIT: macOS 13.3.1

Alpha 6.0 (Apr 21 2023: 09:48:42 UTC): In a brief test `Esc` key did not close image view in a group chat.
EDIT: Same for 1:1 chat with Alpha 6.0 (Apr 22 2023: 17:15:18 UTC).

**Comment by tmolitor-stud-tu** [comment]
@angelina-p09 did you test your PR?

**Comment by angelina-p09** [comment]
> @angelina-p09 did you test your PR?

yes, I tested my pr but I was only able to test it using simulators of iPad and phones for 1:1 and didn't test for groups. I do not have a developer account to run a Mac. I apologize I should have tested it more.

**Comment by angelina-p09** [comment]
> Alpha 6.0 (Apr 21 2023: 09:48:42 UTC): In a brief test `Esc` key did not close image view in a group chat. EDIT: Same for 1:1 chat with Alpha 6.0 (Apr 22 2023: 17:15:18 UTC).

hello @foss-  & @tmolitor-stud-tu !

I looked into the issue a bit further and I was wondering what MacOS version are you running. I think I have an idea of why the issue was not completely fixed. I saw that two other key commands were passed through this condition in order for them to work over the system's default.
https://github.com/monal-im/Monal/blob/b29a478549fdf0928af579a678eb314370971711/Monal/Classes/chatViewController.m#L2831-L2834
 I believe that if the same property is set to true for the escape key, then when pressing the escape key it will close the image preview. I currently am unable to test the theory as I do not have permission to build a MacOS app because I am not on the developer team. (shown in the image below) Is there somehow I can be added to the developer team so I can further test the code?

<img width="560" alt="Screen Shot 2023-04-23 at 9 50 38 PM" src="https://user-images.githubusercontent.com/124469658/233904868-670c0886-d18b-47d4-a06d-093657fef131.png">

**Comment by foss-** [comment]
macOS 13.4
Monal Alpha 6.0 (Jun  1 2023: 20:51:30 UTC)

Sorry to report that pressing `esc` key still does not close image view in my test.

**Comment by FriedrichAltheide** [comment]
Working since Monal 6.0 release

**Comment by foss-** [comment]
Verified in Alpha 6.0.1 (Nov  4 2023: 10:14:25 UTC) and 6.0 (868).

Thanks this is a very welcome change.
