### ISSUE TITLE
Do not enable deleting of messages in public MUCs

### ISSUE THREAD

**Issue by roman901** [monal-im/Monal#680]
<img width="232" alt="Снимок экрана 2021-07-02 в 14 11 27" src="https://user-images.githubusercontent.com/2963008/124266250-65aa1500-db3f-11eb-88b4-af593b8e0c8b.png">
MUC message menu has:
1. Reply button
2. Copy button
3. Remove button

1. How I can mention user? Maybe add a "mention button" at first place
2. Does really MUC need "remove" button/swipe to exist? This may be a little confusing (for example, I removed message accidentally while taking screenshot).

Thanks :)

**Comment by Echolon** [comment]
The first one is not yet implemented and referenced by #636

**Comment by roman901** [comment]
Mentioned issue talking about chat command. I suggest to add a "mention" button into message menu also

**Comment by tmolitor-stud-tu** [comment]
The delete will use last-message-correction to replace the message with a dummy one. Deleting/correcting a message will work in all sorts of mucs and clients usually honor LMC even in channel-type mucs.
Locally deleting older messages can be useful as well (1:1 and muc).
--> I don't see why removing that button would be good, I'm sure shortly after removing it somebody else will come over and ask why we'd not allow deletingmessages in mucs.

Please add your mention button suggestion into #636 I'm closing this issue here.
