### ISSUE TITLE
Freezes while history syncing

### ISSUE THREAD

**Issue by roman901** [monal-im/Monal#687]
While Monal syncing history via MAM for long period (right now - for month) , interface becomes totally unresponsive. New messages (fresh) in chat appears with delay, sending also delayed.

**Comment by Echolon** [comment]
So this appears after registering a new account?

**Comment by roman901** [comment]
No, I’m just opened Monal at PC first time in a month

**Comment by Echolon** [comment]
Can you elaborate what you Monal Mac version is?

3 jul. 2021 12:21:42 PM Roman Shishkin ***@***.***>:

**Comment by roman901** [comment]
I’m using 5.0 beta from website everywhere

**Comment by tmolitor-stud-tu** [comment]
"delayed" is no exactly "freezing", right?

Well, Monal isn't supposed to be used with gaps of several week or even month within.
If you use your account with another client in the meantime there will be a lot of stuff to synchronize and yes, that makes the app somewhat slow, that's expected, it is doing heavy work at least.

If you don't want it to sync in missing parts you can always delete the account and add it back in.
That way it won't try to download the missing history since last usage.

I'm closing this.

**Comment by roman901** [comment]
Ok, but _freezes_ exists anyway. Switching within chats extremly slow and causes UI freezes.

**Comment by tmolitor-stud-tu** [comment]
On my test device it does not freeze that much,maybe your device is older. but anyways there is not much I can do about that.
I can slow down the sync process to leave more room for ui, but that essentially makes the sync last even longer, something not everybody likes.

**Comment by roman901** [comment]
I'm using Hackintosh on Ryzen 5 1600 and MacBook Pro 13" 2020 with i7 - and both freezes similar.

**Comment by tmolitor-stud-tu** [comment]
Well, that's strange, indeed.


Am Samstag, 3. Juli 2021, 23:12:58 CEST schrieb Roman Shishkin:
> I'm using Hackintosh on Ryzen 5 1600 and MacBook Pro 13" 2020 with i7 - and
> both freezes similar.
