### ISSUE TITLE
Kerio Connect: support presence

### ISSUE THREAD

**Issue by alexanderharm** [monal-im/Monal#744]
### 

- [X] I understood that this template is only for feature requests and not for bug reports

### 

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### Describe your feature

It would be great if Monal could support Kerio Connect's XMPP server. Currently it is possible to connect but presence/status is not working (it does using Adium and Kerio's own client). Users always show as online.

I can provide a test account if needed.

**Comment by tmolitor-stud-tu** [comment]
It seems your other clients don't support [XEP-0319: Last User Interaction in Presence](https://xmpp.org/extensions/xep-0319.html) from 2017, which will make the client show the correct online status (e.g. `last online 5 minutes ago`, `currently online` etc.).

You can use a modern client with support for XEP-0319 like Conversations for Android or Gajim for Linux/Wndows desktops.

Without support for XEP-0319 every client will show as online as long as it is able to receive messages (yes, that's a bit simplified but good enough for this purpose).
Monal is able to receive messages even if it is not in the foreground, hence it is shown as "online" in these old clients.

**Edit: removed Dino from the recommendation list because it apparently does not support XEP-0319**

**Comment by alexanderharm** [comment]
Sorry, I think there is a misunderstanding.

I have two users A and B. User A installs Monal and hooks up to the company Kerio Connect server. In Monal of User A all other users show as online even though they are not connected in any way shape or form.

In Adium and Kerio Connect client these other user correctly show as offline.

So I guess Kerio propagates presence status via a protocol/extension that is not supported by Monal.

**Comment by tmolitor-stud-tu** [comment]
Historically in XMPP `online` meat _client is connected_ and `offline` meant _client is NOT connected_.
That did not mean an offline client wasn't able to receive the messages sent to it while it was offline: if it was the only client used, the messages were put nto an offline storage on the server and got delivered when the client connected (e.g. went online) the next time.
If the user used several clients on different devices, these "offline messages" got delivered to the first client that connected, other clients did not get these messages at all.

Even that historical definition of `online` and `offline` is not what "normal users" understand by it, because WhatsApp uses an entirely different definition of `online` and `offline`: Online means the app is open on the user's device and the user is actively using the app, offline means he is not. But WhatsApp extended the `offline` state by `last online at ...`.

But nowadays we have mobile apps that can not be connected the whole time. XEP-0198, XEP-0313 and XEP-0357 were invented to synchronize these non-always-conntected devices.
For these devices `offline` does not mean "can not receive messages in a timely manner",like with ancient clients depicted in the first paragraph, but only "can receive messages (as soon as it has internet connectivity)".

XEP-0319 tries to replicate the WhatsApp definition of `online` and `offline` to make users more happy and give them a wording they are already used to.

**Now to your problem:**

1. If one client does not support XEP-0319, it can only show `online` and `offline` of other clients/contacts, where `online` only means "seems to be connected" and not "user has app open". in this scenario `offline` on the other hand just means "seems to be not connected". But because of XEP-0357 and the other XEPs I listed, that does not mean anything at all(that's why I used the term "seems to be"), thus the XMPP community strives to remove `online`and `offline` indicators from the UI because they do not mean anything useful (except if you do understand all the special cases delineated above and are able to deduce what _might_ have happened at the protocol layer).
2. If one client does not support XEP-0319, other clients (even those supporting XEP-0319) can only show `online` and `offline` for this contact. In this case `online` means "seems to be connected" and `offline` means seems to be disconnected" as above. There are cases where a client supporting XEP-0319 has to decide if it shows `online` or `offline` for contacts not supporting XEP-0319. For Monal we chose to show `online` to indicate that these contacts are likely being able to receive messages even if they are not currently connected to the XMPP server at the protocol layer **(that's why you see some users as `online` in Monal but not in Adium and Kerio Connect)**
3. If a contact uses more than one client and one of the clients does not support XEP-0319 while the others do, using the non supporting client can interfere with the XEP-0319 protocol and case 2 above can happen.
4. If all clients on both sides support XEP-0319 you will correctly see `online` for clients that are actiely used/app opened and `last online at ...` for those that aren't, like WhatsApp would do.

--> Your solution is to use modern clients on all devices (your's and your contact's devices).
--> Or: ignore the `online`/`offline` indicators alltogether

**Comment by truenicoco** [comment]
@tmolitor-stud-tu Would you consider sending `<presence type="available"><show>away</show>…` when last seen is above a certain threshold? I'm asking because AFAIK XEP-0319 does not say we have to completely ditch "away" "dnd" and "chat", which still have some value IMHO.

**Comment by tmolitor-stud-tu** [comment]
Imho every receiving client can just decide to not display the time but something else if it is above a certain threshold.
