### ISSUE TITLE
[Feature]: Voice message / Audio from conversations

### ISSUE THREAD

**Issue by lugau45** [monal-im/Monal#747]
### 

- [X] I understood that this template is only for feature requests and not for bug reports

### 

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### Describe your feature

Unfortunately Monal cannot play adiochats sent from conversations (android). The chats are in m4a format. What Monal sends works on Android without problems.

**Comment by FriedrichAltheide** [comment]
https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions#why-isnt-featureui-implemented-or-bug-fixed

**Comment by lugau45** [comment]
so is it still in work right?

**Comment by Echolon** [comment]
I rather would treat this as bug or non-complete feature.

**Comment by Echolon** [comment]
#362

**Comment by lugau45** [comment]
ok, then let's hope that it is still fixed.

**Comment by zamordek** [comment]
I'm experiencing the same issue with OMEMO-encrypted audio messages in Monal on multiple devices (iOS 18.4 and 18.4.1).

## 🔍 Problem Description

- After sending an **audio message with OMEMO enabled**, the file appears in the chat with the media player (play button and QuickTime icon).
- Tapping the play button does **nothing** — the media does not play.
- However, after **restarting the Monal app**, the exact same audio message becomes playable.
- This issue is **100% reproducible** and occurs **only on the sender’s side**.  
- The **recipient can play the audio immediately** with no restart required.

## ✅ Confirmed Behavior

| Action                               | Result                              |
|--------------------------------------|-------------------------------------|
| Send OMEMO-encrypted audio           | ✅ Message appears in chat          |
| Tap play button on sender side       | ❌ No playback                      |
| Restart Monal                        | ✅ Playback of sent audio works     |
| Recipient receives & plays message   | ✅ Works immediately                |
| Unencrypted audio message            | ✅ Plays immediately on sender side |

## 🧩 Likely Cause

This seems to be a bug in how **Monal handles self-sent OMEMO-encrypted media**:

- The media player is initialized, but the `aesgcm://` stream may not be **cached, decrypted, or linked** correctly for the sender.
- After restarting Monal, cached messages are reloaded, and playback then works.
- This only affects **self playback** after sending — not receiving or uploading.

## ⚠️ Additional Observation

- The **recipient sees an OMEMO decryption warning**, such as:
  > “This message was encrypted using OMEMO but could not be decrypted.”
- Despite this, the recipient can **still play the audio**.
- This suggests that Monal might:
  - Not encrypt the file key for **all known devices** of the recipient.
  - Use outdated or partial OMEMO device lists.

## 📌 Summary

- This is **not an iOS issue** (tested on 18.4 and 18.4.1, multiple devices).
- Likely a client-side bug in **media decryption/init for self messages**.
- Possibly also an issue in **OMEMO device management** during media encryption.

Please let me know if I can provide logs, example messages, or steps to reproduce. The bug is very consistent.

**Comment by tmolitor-stud-tu** [comment]
Will be fixed by chatui rewrite

**Comment by p42ity** [comment]
@lugau45 @zamordek : This has been fixed by the Monal team in https://github.com/monal-im/Monal/releases/tag/Build_iOS_1078 which is currently in Beta. I cannot reproduce this bug anymore.
