### ISSUE TITLE
[Bug]: Valid messages are silently discarded

### ISSUE THREAD

**Issue by stigger** [monal-im/Monal#803]
### What Monal Release channel are you using?

AppStore

### iOS system version

15.4

### iOS Monal version

5.1.0

### Used XMPP server (domain)

own.jabber.server

### Which XMPP-Server software are you using?

ejabberd

### XMPP Server Software Version

21.4.0

### How many accounts are you using in Monal?

1

### What happened?

Starting from v5.1.0, Monal incorrectly assumes that message IDs are unique, which is incorrect:
```
   The optional 'id' attribute MAY be used by a sending entity for
   internal tracking of stanzas that it sends and receives (especially
   for tracking the request-response interaction inherent in the
   semantics of IQ stanzas).  It is OPTIONAL for the value of the 'id'
   attribute to be unique globally, within a domain, or within a stream.
```

There are clients (e.g. @psi-im) that use sequential ids for stanzas. So, whenever such client is restarted, Monal is not going to see any messages from it until the id exceeds the last seen.

### Anything else?

Bisect points at f020deddc06f3c5fcb9f7058c4d5d32512cdf51a.

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkboxes are ticked under Settings --> Notifications

**Comment by tmolitor-stud-tu** [comment]
I fixed this, but you will get a lot of duplicated messages, especially if you use psi alongside of monal in the same account.
The correct fix would be to add support for XEP-0359 in psi.

**Comment by tmolitor-stud-tu** [comment]
And LMC, chat markers, message receipts etc. won't work anymore, see the commit message for details.

**Comment by stigger** [comment]
Thank you for fixing, but the commit message feels unnecessary aggressive towards clients which have been around for decades. Without those "broken" clients and their loyal users there would be no XMPP. The power of XMPP is in the open standards and compatibility, so let's try and be nicer to each other.

Having said that, I do really appreciate the quick fix.

**Comment by stigger** [comment]
By the way, LMC, chat markers and message receipts work fine in Psi. To support them, we only need to look for the last message with a given `id`, instead of any message with a given `id`.

**Comment by tmolitor-stud-tu** [comment]
It's right that the RFC does not mandate unique ids but that's a bug in the specification XMPP is struggling with ever since.
Especially in modern days where communication became even more asynchronous: push, stream management and MAM can cause responses referencing old messages to come in any time, even after other messages having the same id were received.

The only sane solution is to make the ids unique. But that is hard to do while maintaining backwards compatibility. Thus the not really written down consensus in the XMPP world is to fix old software to use unique ids and at the same time let new XEPs not use the id attribute of the message stanza to reference other messages, but the origjn-id or stanza-id (mam id) --> all new XEPs are now using message fastening (XEP 0422) which is based on origin-ids.

The old XEPs will eventually be updated to use message fastening as well or kept in the nimbus of uncertainty like they are now (that's more likely as we are chronically lacking for XEP authors fixing XEPs or writing new ones).

Yes, old clients were (naturally) the first ones to implement XMPP and pave it's path forward, but now they are slowing down progress and cause all sorts of headaches for developers of modern XMPP clients.

**Let me stress this again: the only sane way to get references to other messages stanzas that aren't ambiguous is to make these message stanzas use unique ids. Every client not doing this can cause all sorts of problems and I for my part consider them plain and simple broken. They should be fixed (use uuidv4) or abandoned.**

_I only fixed this bug because I figured discarded messages are more bad than duplicated ones.
But now all references to other messages can only be unambiguous if they use origin-ids --> Monal will from now on only send and/or accept LMC, message receipts, chat markers etc. for messages having an origin-id._

**Comment by stigger** [comment]
I totally understand, and I might even consider implementing unique ids for Psi. My only complaint was about using phrases "screw them" and "nobody needs them". A more neutral tone could have conveyed the point just as well.

Sorry for nagging about it, I will stop now.

**Comment by tmolitor-stud-tu** [comment]
Well, you are right. Some times I'm a bit annoyed of coding workarounds for clients/servers not following modern xmpp stuff and/or implementing older XEP versions etc. on top of having to work around apple restrictions.
That's the reason for my harsh words in this commit, but your are right, that words were not needed.

> I might even consider implementing unique ids for Psi
That are great news! Just make sure to implement origin-ids as well and set the stanza id and origin-id to the same value.

**Comment by tmolitor-stud-tu** [comment]
After discussing with Holger, I pushed a better fix now.

**Comment by Echolon** [comment]
FYI @ri0n

**Comment by Ri0n** [comment]
I've merged a PR from @stigger which I believe implements exactly what he mentions above.
