### ISSUE TITLE
[Feature]: UI tweaks for new contact view

### ISSUE THREAD

**Issue by foss-** [monal-im/Monal#814]
### Precondition

- [X] I understood that this template is only for feature requests and not for bug reports

### Cross-checked related issues?

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### Describe your feature

UI tweaks for new contact view:

- [ ] Relation from image to test seems off. Contact / Channel image could be slightly smaller.
- [ ] When there is enough space available the contact view should show be large enough to show all options (especially on macOS there is likley enough screen estate) and not be a scrollable view.
- [ ] Nickname textbox should align with options on left side, currently it looks random.
- [ ] Not sure why there is so much space around `Pin Chat` option in the screenshot below. If possible remove space.
- [ ] In its current size, the `#` for channels looks blurry. Make it sharp. Maybe this is a non issue if contact image size is slightly decreased.

![1](https://user-images.githubusercontent.com/5708172/170664489-b7a35f8e-1822-4609-b0be-27f53e917454.png)

**Comment by tmolitor-stud-tu** [comment]
>  Relation from image to test seems off. Contact / Channel image could be slightly smaller.

The contact image size is intentional to allow users to see details of the image.

>  When there is enough space available the contact view should show be large enough to show all options (especially on macOS there is likley enough screen estate) and not be a scrollable view.

Unfortunately the catalyst builds restrict the size of the view, currently we can not fix this.

> Nickname textbox should align with options on left side, currently it looks random.

@janst97 can you fix this? Why does the nickname input sit in the top frame at all? And why is it visible for groups/channels at all? Setting a "nickname" converts the muc to a normal contact and breaks everything.

> Not sure why there is so much space around Pin Chat option in the screenshot below. If possible remove space.

That's because it sits in its extra frame like for normal contacts, but the frame does not contain the other 2 options present for normal non-muc contacts. You can see the frame if you disable dark mode.

>  In its current size, the # for channels looks blurry. Make it sharp. Maybe this is a non issue if contact image size is slightly decreased.

That's because the size of the # resembles the size of the profile image. When the image is really small, the # will be really small, too and later scaled up when displayed as big image in the contact details.

**Comment by tmolitor-stud-tu** [comment]
nickname view fixed in alpha, closing now
