### ISSUE TITLE
Mute certain notifications.

### ISSUE THREAD

**Issue by gitbq** [monal-im/Monal#864]
Great job with the latest update. 

Is there any way to silence certain notifications, or does apple have an all or nothing approach?

It would be great if it was possible to silence the "could not synchronise" notifications.

**Comment by tmolitor-stud-tu** [comment]
You can silence notifications from specific contact using the bell icon in the contact details.

The could not synchronize notification on the other hand is a sign that something does not work like it should.
I try to explain a bit, how Monal works internally:
If you put the app into the background or even swipe it away, iOS will freeze 
the app (meaning it won't run nor have any connection to your XMPP server at 
all) until you reopen it again.
But when using a modern messaging app you would expect it to still receive 
messages and show you notifications for incoming messages.
To still accomplish this while the app is frozen, Monal implements push 
notifications (XEP-0357).
Your XMPP server will send a push to Monal's appserver (operated by us) if 
something new happens (that can be incoming 1:1 messages, message receipts or 
read indications, new groupchat/channel messages etc.).
The appserver then sends a push through Apple's system to wake up the App in 
the background. Monal then connects to the XMPP server to retrieve the 
original message and show a notification (e.g. synchronize).

Not all pushes trigger a visible notification though (read indications, 
messages of muted 1:1 or groupchat/channel contacts etc.).

iOS grants only 30 seconds of background time for every incoming push. Thus, 
if Monal does not manage to connect to the XMPP server to retrieve the pending 
data, it will show a notification saying it could not synchronize.
Because the push does not contain any data at all, Monal can't know if it 
missed something important in this case unless it managed to contact the XMPP 
server to retrieve the pending data.
That's why it shows a "could not synchronize" notification in these cases.

Normally all of this should not be a problem and the synchronization in the 
background should be smooth and only take a couple of seconds (usually around 
4 to 10 seconds).
In your case, though, it seems to not manage to connect to the XMPP server.
So, rather than adding an option into Monal which would allow to turn off 
these errors, I'd like to fix the bug/problem you are experiencing to make 
the synchronization work as intended again.

Sidenote: if you have an issue, please use the issue templates provided, if not, please use the github discussions instead: https://github.com/monal-im/Monal/discussions

**Comment by gitbq** [comment]
Thanks for the information.
No worries, I'll try the discussions next time.
