### ISSUE TITLE
Can't play .mp3 audio attachments

### ISSUE THREAD

**Issue by hollymrklm** [monal-im/Monal#866]
### What Monal Release channel are you using?

AppStore

### iOS Monal version

5.3.3

### Used XMPP server (domain)

(private)

### How many accounts are you using in Monal?

1

### What happened?

Monal can't play successfully received mp3 audio attachments. I can see playback controls, but the play/pause button seems greyed out and it is not responding. It looks visually similar to screenshot from closed ticket #789. I tried other formats too with more (or less) success: wav works normally, flac works quite normally (the play/pause button seems confused sometimes, but no big deal) and ogg (oga) is not recognized as audio file at all...

Tested with same results on two devices (SE I. and 6) with Monal 5.3.3, both 1to1 (omemo) and MUC (no omemo) chats.

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by unriccio** [comment]
I had a similar experience but didn't investigate/correlate with the file formats...

In my case I tried to send an audio message:
- from Monal to Conversations: the play button is white/clickable but when I push it it toggles (and immediately switches back) and Monal does not replay the audio message that it just sent
- from Conversations to Monal: grayed play button, cannot be clicked at all

I don't think it's related to the file format because if I send back the same AAC file (Monal > Conversations > Monal, copy/pasting the URL on Conversations to ensure I'm sharing the same file) then Monal is not able to play it.
It actually stops replaying also the previous message that was originally recorded :|

Some further weirdnesses:
1. in some cases swiping away Monal made the audio messages playable again
2. in a few attempts Monal asked to download the audio but said that the file size was zero bytes
3. when locking the screen after successfully playing an audio message (the play button switches back, nothing can be heard), the phone lockscreen will still show Monal and will allow to replay the same audio message - this doesn't happen if I swipe away Monal after playing the message
(not sure if these help or not, and maybe the last one should warrant a bug report by itself?) :)

Tested on Monal 5.3.3 from appstore, account on magicbroccoli.de

**Comment by madfoss** [comment]
Voice messages no longer work on several iPhones running iOS 16.1.1 and Monal 5.3.4 from the Apple Store. Only a black field appears in the chat window with no controls or function.

**Comment by FriedrichAltheide** [comment]
We accept PRs

**Comment by Echolon** [comment]
- [Bug]: Receive audio recordings, can't play them #789 
- [Feature]: Voice message / Audio from conversations #747
- Audio: File not playable and shows empty screen #362

**Comment by tmolitor-stud-tu** [comment]
Is this bug still present in 6.0?

**Comment by tmolitor-stud-tu** [comment]
no response, closing

**Comment by thanosapollo** [comment]
> Is this bug still present in 6.0?

Yeah, I'm trying out monal, sending a voice reconding from conversations/cheogram is not playable

EDIT: One workaround is to have VLC installed & use the VLC app to play the audio recordings

**Comment by licaon-kter** [comment]
@thanosapollo are you sure you sent from Conversations 2.15.3 or 2.16.0 and it didn't play?

**Comment by thanosapollo** [comment]
cheogram latest version from fdroid & monocles actually.  I can do further tests if you like.


Attaching images:

![AC301A22-F9F3-4176-BD5C-6AECA50CDF3C](https://github.com/monal-im/Monal/assets/138289036/29370404-f0b5-4748-804b-0c2e4e368ad3)
![E34A0869-C5BC-4C23-8115-E9A462BA1096](https://github.com/monal-im/Monal/assets/138289036/16e904b9-4124-4d8a-8e3a-bd9077aabac0)

**Comment by thanosapollo** [comment]
upon further investigation, it seems that monal can play m4a files, but not ogg audio.

@licaon-kter  tested with:
- Cheogram 2.13.4-1
- Coversations 2.15.3

**Comment by licaon-kter** [comment]
@thanosapollo yes, Conversations initiated a change to Opus (.ogg) but after feedback from Monal (or iOS users in general) that was reverted.

Cheogram and Monocles are forks, so they do as they please.

Hence, while testing, provide info about the tested client exactly, don't say Conversations if you test Monocles...
