### ISSUE TITLE
[Bug]: Migration assistent stating Monal iCloud backup restored despite iCloud never active

### ISSUE THREAD

**Issue by germanicianus** [monal-im/Monal#947]
### What Monal Release channel are you using?

AppStore

### macOS Monal version

5.4.4 (845)

### Used XMPP server (domain)

wiuwiu.de

### Which XMPP-Server software are you using?

None

### How many accounts are you using in Monal?

1

### What happened?

See issue subject and below screenshot.
<img width="421" alt="monal_icloud_message_despit_disabled" src="https://github.com/monal-im/Monal/assets/37223176/f2da312b-748c-4c4e-9a31-3202f83bf982">

### FAQ

- [X] I have [checked the FAQ](https://github.com/monal-im/Monal/wiki/FAQ---Frequently-Asked-Questions) for my issue

### Considerations for XMPP users

- [X] I have checked if my issue can be solved with [Considerations for XMPP users](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-users) and [Considerations for XMPP server admins](https://github.com/monal-im/Monal/wiki/Considerations-for-XMPP-server-admins)

### Related Issues

- [X] I have cross-checked this overview https://github.com/monal-im/Monal/issues/322 as well as filtered for related labels https://github.com/monal-im/Monal/labels

### XEP-Check

- [X] I have checked that at least XEP-198, XEP-0280, XEP-0352, XEP-0357, XEP-0313 and XEP-0163 are activated on my server and shown as 'green' under Settings --> Account--> (i) in advanced settings

### Notifications-Menu

- [X] I have checked that all checkmarks are present under Settings --> Notifications

**Comment by FriedrichAltheide** [comment]
When was the last time that you used Monal before the error?

**Comment by lissine0** [comment]
In the past I've been building Monal on commit https://github.com/monal-im/Monal/commit/8e49546 (+ some local changes)
But now I've pulled the latest commits from the develop branch. And a similar thing just happened to me on the Xcode Simulator (iphone 8 on iOS 16.2)
![Simulator Screen Shot - iPhone 8 - 2023-09-30 at 17 53 06](https://github.com/monal-im/Monal/assets/138154076/8af128cc-8e4e-4511-a2b2-cf399ad64e59)

I'm not sure when I last used this device on the simulator, because I also use the iphone SE (2nd generation) as well as a physical device.
But I probably used it a month ago.

**Comment by germanicianus** [comment]
@FriedrichAltheide, I think the Monal version I used before was the old one before the Monal developer account change. I didn't make a screenshot of the dialog stating that it changed. This issue is just about the misleading iCloud statement. I didn't loose any data/chat history despite I removed the old Monal and installed the new one from the Mac AppStore as requested in the dialog about the developer account change. I think this is because the settings were preserved as usual with MacOS and Linux.

**Comment by tmolitor-stud-tu** [comment]
yes, there are two things triggering the migration dialog:

1. an actual icloud restore
2. the developer account change

It's now about a year since the developer account change and I suspect there will be many people still getting this dialog because of that account change.
Hence I don't want to change the text and add the second reason: the text would grow and not fit nicely beneath the logo, but give little to no benefit.
